services:
  amr-health:
    build:
      context: .
      dockerfile: Containerfile
    container_name: AMR-Health
    ports:
      - "8088:8090"
    volumes:
      - ./data:/app/data
    restart: unless-stopped