#!/usr/bin/env bash
set -euo pipefail

INSTALL_ROOT="${DRISHTI_INSTALL_ROOT:-/opt/drishti-amr-health}"
SETTINGS_FILE="$INSTALL_ROOT/runtime.env"
[[ -f "$SETTINGS_FILE" ]] || { echo "Missing $SETTINGS_FILE" >&2; exit 1; }

set -a
# The file is generated by the installer with shell-safe values and mode 0600.
source "$SETTINGS_FILE"
set +a

mkdir -p "$INSTALL_ROOT/data/config" "$INSTALL_ROOT/data/ssh" \
  "$INSTALL_ROOT/data/rds-snapshots" "$INSTALL_ROOT/data/keys"
touch "$INSTALL_ROOT/data/ssh/known_hosts"

podman network inspect drishti-amr-health-runtime >/dev/null 2>&1 || \
  podman network create drishti-amr-health-runtime >/dev/null
podman volume inspect drishti-amr-health-runtime-db >/dev/null 2>&1 || \
  podman volume create drishti-amr-health-runtime-db >/dev/null

if podman container exists AMR-Health-DB; then
  podman start AMR-Health-DB >/dev/null 2>&1 || true
else
  podman run -d --name AMR-Health-DB \
    --network drishti-amr-health-runtime --network-alias database \
    --restart unless-stopped \
    -e POSTGRES_USER=amr -e "POSTGRES_PASSWORD=$DATABASE_PASSWORD" \
    -e POSTGRES_DB=amrdashboard \
    -v drishti-amr-health-runtime-db:/var/lib/postgresql/data \
    docker.io/library/postgres:16-alpine >/dev/null
fi

secret_args=()
if podman secret inspect drishti_llm_api_key >/dev/null 2>&1; then
  secret_args=(--secret drishti_llm_api_key,target=llm_api_key)
fi

database_url="postgres://amr:${DATABASE_PASSWORD}@database:5432/amrdashboard?sslmode=disable"
podman run -d --replace --name AMR-Health \
  --network drishti-amr-health-runtime --restart unless-stopped \
  -p "0.0.0.0:${HOST_PORT}:8090" \
  -v "$INSTALL_ROOT/data:/app/data:Z" \
  -v "$INSTALL_ROOT/data/ssh/known_hosts:/app/known_hosts:ro,Z" \
  -e PORT=8090 -e DRISHTI_STATIC_DIR=/app/frontend/dist \
  -e DRISHTI_API_CONFIG=/app/data/config/api-connections.json \
  -e "DATABASE_URL=$database_url" \
  -e "ENCRYPTION_KEY=$ENCRYPTION_KEY" -e "SESSION_SECRET=$SESSION_SECRET" \
  -e "ALLOWED_ORIGINS=$ALLOWED_ORIGINS" \
  -e "OLLAMA_URL=$LLM_URL" -e "OLLAMA_MODEL=$LLM_MODEL" \
  -e LLM_API_KEY_FILE=/run/secrets/llm_api_key \
  "${secret_args[@]}" localhost/drishti-amr-health:runtime >/dev/null

for _ in $(seq 1 30); do
  if curl -fsS "http://127.0.0.1:${HOST_PORT}/api/health" | grep -q '"ok":true'; then
    echo "DRISHTI AMR Health is ready at $PUBLIC_URL"
    exit 0
  fi
  sleep 2
done

echo 'AMR Health did not become healthy. Run: podman logs AMR-Health' >&2
exit 1
